name: KPMG frontend deployment to Azure VM

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to KPMG VM
        uses: appleboy/ssh-action@master
        with: 
             host: ${{ secrets.KPMG_IP }}
             username: ${{ secrets.KPMG_USERNAME }}
             #password: ${{ secrets.TESTVM_PASSWORD }}
             key: ${{ secrets.KPMG_SSH_KEY }}  
             script: |
              git clone https://github.com/George-Jovin/Customer360.git /home/$(whoami)/deployment_git ; sudo rm -rf /var/www/html/* ; sudo cp -r /home/$(whoami)/deployment_git/build/* /var/www/html/ ; rm -rf /home/$(whoami)/deployment_git/ ; sudo systemctl restart nginx
